# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # Microsoft-hosted agent

jobs:
- job: RunInsomniaTests
  displayName: 'Run Insomnia API Tests'
  steps:

    # Install Node.js (required for insomnia-cli)
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    # Install insomnia-cli globally
    - script: |
        npm install -g insomnia-cli
      displayName: 'Install insomnia-cli'

    # Run the Insomnia collection
    - script: |
        insomnia-cli run ./demo.yaml
      displayName: 'Run Insomnia Collection'