# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'  # Microsoft-hosted agent

jobs:
- job: RunInsomniaTests
  displayName: 'Run Insomnia API Tests'
  steps:

    # Install Node.js (required for insomnia-cli)
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    # Install insomnia-cli globally
    - script: |
        brew install inso
      displayName: 'Install insomnia-cli'

    # Run the Insomnia collection
    - script: |
        inso run collection demo -r junit > results.xml
      displayName: 'Run Insomnia Tests'

    # Publish results to Azure DevOps Test tab
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'results.xml'
        testResultsFormat: 'JUnit'
        failTaskOnFailedTests: true
      displayName: 'Publish Test Results'
